### ISSUE TITLE
Installing module

### ISSUE THREAD

**Issue by stevro** [firstred/mdrefchange#1]
Hi,

I'm trying to install this module on prestashop 1.6.1
It says success but I don't see it in the list.
Is it compatible with PS 1.6.1?

Thanks.

**Comment by firstred** [comment]
This module is far from finished atm. In my repositories, if there is no release tag you may assume that the module has no stable or test version, yet.

**Comment by stevro** [comment]
I also tried with tag 1.3.0 but still didn't work.
